from .schemas import Source

sources: list[Source] = [
    Source(
        id="return-policy",
        title="退换货政策说明",
        category="售后政策",
        url="https://example.com/support/returns",
        status="indexed",
        updatedAt="2026-09-01",
        description="说明商品退换货条件、申请流程、运费规则和退款时效。",
    ),
    Source(
        id="shipping-policy",
        title="订单与物流说明",
        category="订单服务",
        url="https://example.com/support/shipping",
        status="indexed",
        updatedAt="2026-09-02",
        description="说明发货时间、物流查询方式、配送范围和异常处理。",
    ),
    Source(
        id="invoice-policy",
        title="发票申请说明",
        category="财务服务",
        url="https://example.com/support/invoice",
        status="pending",
        updatedAt="待更新",
        description="说明电子发票申请入口、开票信息填写和重开规则。",
    ),
    Source(
        id="account-policy",
        title="账号与会员说明",
        category="账号服务",
        url="https://example.com/support/account",
        status="indexed",
        updatedAt="2026-09-03",
        description="说明账号注册、登录、密码找回和会员权益。",
    ),
    Source(
        id="human-service",
        title="人工客服转接说明",
        category="服务渠道",
        url="https://example.com/support/human",
        status="pending",
        updatedAt="待处理",
        description="说明人工客服入口、服务时间和排队规则。",
    ),
]
